### PR TITLE
test(go-core): cover workload retry policy

### LINKED ISSUE #52: E2E: validate workload start retry + fast retry after config fix
## User request
Add an end-to-end test (go-core suite, agents-orchestrator) that exercises the new workload start retry policy behavior:

- Start with a **broken agent configuration**
- Send a **new message**
- Observe workload **start failure** and correct **failure attribution**
- **Fix the agent configuration**
- Verify the orchestrator **retries quickly** (config-driven fast retry) and the agent eventually **responds**

Source of truth: https://github.com/agynio/architecture/blob/main/changes/2026-04-24-workload-start-retry-policy.md

### Failure mode to induce (deterministic)
Use **`config_invalid` via an invalid `Agent.init_image` reference**.

Rationale: avoids registry/network flakiness (`image_pull_failed`) and avoids reliance on runtime behavior (`crashloop`). Kubernetes deterministically surfaces invalid image references as config errors.

Concrete break:
- Create the agent with an intentionally invalid `init_image` string, e.g. `"INVALID_IMAGE_NAME:latest"`.
- Keep the agent’s main `image` and model valid.

### Assertions
Observe via **RunnersService (state service)**, **ThreadsService**, and **RunnerService (k8s runner)**:

1) After sending the message, the orchestrator should produce **two consecutive failed workloads** for `(thread_id, agent_id)`:
- `status == WORKLOAD_STATUS_FAILED`
- `failure_reason == WORKLOAD_FAILURE_REASON_CONFIG_INVALID`
- `failure_message` non-empty
- `removed_at` set
- `instance_id` set
- (optional, tolerant) container list includes at least one container with `status=WAITING` and `reason` in {`InvalidImageName`, `CreateContainerConfigError`, `CreateContainerError`}.

2) The thread should **not** be degraded:
- `Threads.GetThread(thread_id).status == THREAD_STATUS_ACTIVE`.

3) The failed workload should be cleaned up on the runner:
- For each failed workload, `Runner.InspectWorkload(instance_id)` eventually returns NotFound (pod removed).

4) Fast retry after config fix (bypass backoff)
- After the **second** failure, the next retry would normally be backed off by **30s** (BACKOFF_SCHEDULE[1]).
- Update the agent to a valid init image (`Agents.UpdateAgent(init_image=<valid>)`).
- Assert the orchestrator creates a **new** workload record for the same `(thread_id, agent_id)` **before** the 30s backoff would have elapsed:
  - `new_workload.created_at - failed2.removed_at < 30s`

5) End-to-end recovery
- The agent eventually posts the expected response in the thread (use existing simple-hello model expectation): `"Hi! How are you?"`.

### Placement / build tags
- Add a new Go test under: `suites/go-core/tests/` (suggested file: `workload_start_retry_policy_test.go`)
- Build tags: `//go:build e2e && svc_agents_orchestrator`

### Runtime guidance
- Keep to 2 failures (to reach the 30s backoff step) to bound runtime.
- Use bounded per-phase timeouts (failure1, failure2, post-update fast retry, agent response).

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- add go-core E2E test covering workload start retry failures and config-driven fast retry
- assert failed workload attribution, runner cleanup, and successful agent response after config fix

## Testing
- go test ./... (suites/go-core)
- go vet ./... (suites/go-core)

Closes #52

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Testing
- go test ./... (suites/go-core) (passed: all, failed: 0, skipped: 0)
- go vet ./... (suites/go-core) (lint: no errors)

File: suites/go-core/tests/workload_start_retry_policy_test.go [hunk 1]
```diff
@@ -0,0 +1,448 @@
...
+	failureCtx, failureCancel := context.WithTimeout(ctx, failedWorkloadTimeout)
+	defer failureCancel()
+	failedWorkloads, err := waitForFailedWorkloads(failureCtx, runnersClient, threadID, agentID, 2)
+	if err != nil {
+		t.Fatalf("wait for failed workloads: %v", err)
+	}
+	if len(failedWorkloads) < 2 {
+		t.Fatalf("expected at least 2 failed workloads, got %d", len(failedWorkloads))
+	}
+	failedLatest := failedWorkloads[0]
```
Comment (noa-lucent) [inline suites/go-core/tests/workload_start_retry_policy_test.go:120]: [major] This test assumes ListWorkloadsByThread returns workloads in a stable newest-first order (e.g. failedWorkloads[0]/[1] and allWorkloads[0]/[1] are treated as the most recent attempts). If the API ordering changes or is undefined, we can pick the wrong failure for removedAt and either get flakiness or stop measuring the intended 30s backoff step.\n\nPlease sort workloads explicitly by meta.created_at (desc) before indexing, and when locating the retry workload consider selecting the *earliest* non-failed workload created after removedAt (min created_at > removedAt) so the backoff delta is measured against the first retry attempt.

File: suites/go-core/tests/workload_start_retry_policy_test.go [hunk 2]
```diff
@@ -0,0 +1,448 @@
...
+
+	sentMessage := sendMessage(t, threadsCtx, threadsClient, threadID, identityID, "e2e workload start retry")
+	sentMessageTime := messageCreatedAt(t, sentMessage)
+
+	labels := map[string]string{
+		labelManagedBy: managedByValue,
+		labelAgentID:   agentID,
+		labelThreadID:  threadID,
+	}
+	t.Cleanup(func() {
```
Comment (noa-lucent) [inline suites/go-core/tests/workload_start_retry_policy_test.go:100]: [minor] Cleanup uses the test ctx (which may be at/over its deadline on failures/timeouts). Prefer creating a fresh cleanup context (e.g. context.WithTimeout(context.Background(), testTimeout)) inside t.Cleanup so we still attempt workload cleanup even if the main ctx expired.

File: suites/go-core/tests/workload_start_retry_policy_test.go [hunk 3]
```diff
@@ -0,0 +1,448 @@
...
+func workloadCreatedAt(t *testing.T, workload *runnersv1.Workload) time.Time {
+	t.Helper()
+	created := workloadCreatedAtErr(workload)
+	if created.err != nil {
+		t.Fatal(created.err)
+	}
+	return created.time
+}
+
+type workloadTimeResult struct {
```
Comment (noa-lucent) [inline suites/go-core/tests/workload_start_retry_policy_test.go:486]: [nit] workloadCreatedAtErr returning a custom workloadTimeResult struct feels unnecessary. Idiomatic Go would be (time.Time, error), which removes the extra type and makes call sites a bit clearer.

**Review by noa-lucent — CHANGES_REQUESTED** [review]
Requesting changes.

The test looks aligned with #52, but it currently assumes ListWorkloadsByThread returns workloads in a stable newest-first order. That’s not a safe invariant to build the backoff timing assertion on; please sort workloads explicitly by meta.created_at (and ensure the retry workload used for the delta is the first attempt after removedAt).

Minor: consider using a fresh context inside t.Cleanup so cleanup still runs if the main ctx expires.

**Comment by casey-brooks** [comment]
## Summary
- explicitly sort workloads by created_at for failure ordering
- select the earliest workload created after removed_at for the fast-retry delta

## Testing
- go test ./... (suites/go-core) (passed: all, failed: 0, skipped: 0)
- go vet ./... (suites/go-core) (lint: no errors)

File: suites/go-core/tests/workload_start_retry_policy_test.go (hunk 1 above)
Comment (noa-lucent) [reply suites/go-core/tests/workload_start_retry_policy_test.go:120]: Confirmed fixed: workloads are now sorted explicitly by meta.created_at before indexing, and the retry workload is selected as the first workload created after removedAt.

File: suites/go-core/tests/workload_start_retry_policy_test.go (hunk 2 above)
Comment (noa-lucent) [reply suites/go-core/tests/workload_start_retry_policy_test.go:100]: Not blocking for approval. Using the main test ctx in cleanup matches other go-core tests; we can improve with a fresh cleanup context in a follow-up if needed.

File: suites/go-core/tests/workload_start_retry_policy_test.go (hunk 3 above)
Comment (noa-lucent) [reply suites/go-core/tests/workload_start_retry_policy_test.go:486]: Still a nit; OK to keep the workloadTimeResult helper as-is for now.

**Review by noa-lucent — APPROVED** [review]
Confirmed fixes from prior review:
- Workloads are now sorted explicitly by meta.created_at before indexing.
- Retry workload selection uses the first workload created after removedAt, making the fast-retry assertion deterministic.

LGTM.
